"""Assisted source migration — bring legacy source pages up to the source-entity
contract and scaffold the ingestion recipe where a ``source_config`` page has
none.

The transformation is **deterministic and dry-run-first**: it only *adds*
missing keys (never overwrites a value the owner already wrote) and, where it
cannot infer a value, it writes an explicit ``TODO`` placeholder plus a note —
it NEVER invents data. The one replacement it permits is promotion of the exact,
untouched TODO recipe scaffold previously generated by this module. Every
applied change is meant to flow through the normal PR gate for a human to
complete and approve.

What it does:

* ``source`` pages gain ``platform`` / ``source_locator`` / ``owner`` (inferred
  from the page, its ``config_ref`` page, or a conservative fallback) and a
  ``sync`` machine block. A versioned ``last_ingested_at`` is preserved as
  proof of an earlier ingestion; only pages without evidence are seeded as
  ``never``.
* ``source_config`` pages with no fenced ``recipe:`` block gain a scaffolded one
  (platform + locator + one content pipeline + a TODO stream) so an agent has a
  manual to complete.
"""

from __future__ import annotations

import datetime as dt
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from wiki_core.config import WikiConfig
from wiki_core.frontmatter import FRONTMATTER_RE, parse_frontmatter
from wiki_core.source_recipe import PLATFORMS, extract_recipe_mapping
from wiki_core.source_schedule import infer_source_kind

# source_type (or a co-located hint) -> platform. Anything unmapped falls back
# to "manual" (a valid platform meaning human-curated / no automated pull), with
# a note so the reviewer confirms it.
_SOURCE_TYPE_PLATFORM: dict[str, str] = {
    "reference": "repo",
    "repository": "repo",
    "repo": "repo",
    "document": "file",
    "file": "file",
    "export": "file",
    "dataset": "file",
    "feed": "web",
    "website": "web",
    "web": "web",
    "chat": "slack",
    "conversation": "slack",
    "email": "gmail",
    "calendar": "calendar",
}

# Platforms whose locator is a repo-local path (so the page's own path is a
# legitimate, non-invented locator). Chat/web platforms need a real external id,
# which we leave as an explicit TODO.
_REPO_LOCATOR_PLATFORMS = frozenset({"repo", "file", "manual"})

_PLATFORM_HINTS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"chatgpt", re.I), "chatgpt"),
    (re.compile(r"whatsapp", re.I), "whatsapp"),
    (re.compile(r"gmail|e[- ]?mail", re.I), "gmail"),
    (re.compile(r"google[ -]?chat|gchat", re.I), "gchat"),
    (re.compile(r"google[ -]?photos|google fotos", re.I), "google_photos"),
    (re.compile(r"google[ -]?(drive|sheets)|\bdrive\b|planilha", re.I), "drive"),
    (re.compile(r"github|gitlab|reposit[oó]rio|\brepo\b", re.I), "repo"),
    (
        re.compile(
            r"linkedin|workday|portal|billing|openfinance|auvp|staking|"
            r"mckinsey|zoom|receita|vaga|collabsoul p[uú]blica",
            re.I,
        ),
        "web",
    ),
    (
        re.compile(
            r"docs?/|data/raw|data/derived|download|transcri|audio|whisper|"
            r"fatura|extrato|arquivo|file[_ -]?bundle|artifact",
            re.I,
        ),
        "file",
    ),
)


@dataclass(frozen=True)
class SourceMigrationChange:
    """One deterministic change to one source/source_config page."""

    rel: str
    page_type: str
    add_frontmatter: dict[str, Any] = field(default_factory=dict)
    append_recipe: str = ""
    replace_recipe_from: str = ""
    replace_recipe_with: str = ""
    notes: tuple[str, ...] = ()

    def is_empty(self) -> bool:
        return not (
            self.add_frontmatter
            or self.append_recipe
            or self.replace_recipe_from
            or self.replace_recipe_with
        )


def infer_platform(values: dict[str, Any]) -> tuple[str, bool]:
    """Return (platform, guessed). ``guessed`` marks a conservative fallback the
    reviewer should confirm."""
    existing = str(values.get("platform") or "").strip()
    if existing in PLATFORMS:
        return existing, False
    # A specific identity is stronger than a coarse legacy type. For example,
    # a page named as a WhatsApp export must not be migrated as Slack merely
    # because its old source_type was "chat".
    hint = " ".join(
        str(values.get(key) or "")
        for key in (
            "page_id",
            "title",
            "source_locator",
            "url",
            "source_url",
            "source_type",
        )
    )
    for pattern, platform in _PLATFORM_HINTS:
        if pattern.search(hint):
            return platform, False
    source_type = str(values.get("source_type") or "").strip().lower()
    mapped = _SOURCE_TYPE_PLATFORM.get(source_type)
    if mapped:
        # A chat/email mapping from a coarse source_type is a real guess.
        return mapped, source_type in {"chat", "conversation", "email"}
    return "manual", True


def infer_locator(rel: str, values: dict[str, Any], platform: str) -> tuple[str, bool]:
    """Return (locator, is_todo). Repo-local platforms use the page path; external
    platforms get an explicit TODO placeholder (never a fabricated id)."""
    existing = str(values.get("source_locator") or "").strip()
    if existing:
        return existing, False
    url = str(values.get("url") or values.get("source_url") or "").strip()
    if platform == "web" and url:
        return url, False
    if platform in _REPO_LOCATOR_PLATFORMS:
        return rel, False
    return f"TODO-{platform}-locator", True


def _contained(root: Path, rel: str) -> Path | None:
    """Resolve a repo-relative path and refuse anything that escapes the repo
    root (``../`` or absolute) — a config_ref must never read arbitrary files."""
    candidate = Path(rel)
    if candidate.is_absolute():
        return None
    resolved = (root / candidate).resolve()
    try:
        resolved.relative_to(root.resolve())
    except ValueError:
        return None
    return resolved


def _config_page_values(root: Path, values: dict[str, Any]) -> dict[str, Any]:
    config_ref = str(values.get("config_ref") or "").strip()
    if not config_ref:
        return {}
    path = _contained(root, config_ref)
    if path is None or not path.is_file():
        return {}
    return parse_frontmatter(path)[0]


def infer_owner(values: dict[str, Any], config_values: dict[str, Any]) -> str:
    """Owner from the page, else the governing config page. Never fabricated."""
    existing = str(values.get("owner") or "").strip()
    if existing:
        return existing
    return str(config_values.get("owner") or "").strip()


def initial_sync(values: dict[str, Any]) -> dict[str, str]:
    """Build the first machine sync block without erasing legacy evidence."""
    ingested_at = str(values.get("last_ingested_at") or "").strip()
    if not ingested_at:
        return {"last_run_at": "", "last_status": "never", "last_event_ref": ""}
    status = "partial" if str(values.get("ingestion_state") or "") == "partial" else "ok"
    return {"last_run_at": ingested_at, "last_status": status, "last_event_ref": ""}


def scaffold_recipe_block(platform: str, locator: str) -> str:
    """A valid-but-placeholder recipe manual. All open decisions are TODOs the
    reviewer completes; the stream is unselected so nothing ingests by accident."""
    recipe = {
        "recipe": {
            "schema_version": "wiki_source_recipe.v1",
            "platform": platform,
            "locator": locator,
            "source_kind": infer_source_kind(platform),
            "pipelines": [{"kind": "content", "cadence_days": 30}],
            "streams": [
                {
                    "id": "todo-stream-1",
                    "label": "TODO: name the channel / folder / export",
                    "selected": False,
                    "privacy": "private_self",
                    "skip_reason": "TODO: set filters + privacy, then select to enable",
                }
            ],
            "how_to_export": "TODO: how an agent ingests this source on demand.",
            "schedule": {"mode": "on_demand", "cadence_days": 0},
        }
    }
    dumped = yaml.safe_dump(recipe, sort_keys=False, allow_unicode=True).rstrip("\n")
    return (
        "## Recipe\n\n"
        "<!-- Assisted-migration scaffold — complete the TODOs and remove this note. -->\n\n"
        f"```yaml\n{dumped}\n```\n"
    )


def _generated_scaffold_in_text(
    text: str, recipe_mapping: dict[str, Any]
) -> str:
    """Return the exact framework scaffold when it is still untouched.

    Reconstructing the block from its own platform and locator makes promotion
    fail closed: removing the marker or editing any recipe field protects the
    block as user-authored content.
    """
    platform = str(recipe_mapping.get("platform") or "")
    locator = str(recipe_mapping.get("locator") or "")
    if not platform or not locator:
        return ""
    candidate = scaffold_recipe_block(platform, locator)
    return candidate if text.count(candidate) == 1 else ""


def _positive_int(*values: Any, default: int = 30) -> int:
    for value in values:
        try:
            number = int(str(value).strip())
        except (TypeError, ValueError):
            continue
        if number > 0:
            return number
    return default


def _list_values(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(item) for item in value if str(item).strip()]
    return []


def _privacy(values: dict[str, Any]) -> str:
    for key in ("sensitive_data_policy", "visibility"):
        value = str(values.get(key) or "").strip()
        if value in {
            "private_self",
            "private_sensitive_allowed",
            "team_shared",
            "public_ok",
        }:
            return value
    return "private_self"


def _operator_auth(platform: str) -> dict[str, Any]:
    if platform in {"drive", "google_photos", "gmail", "gchat", "calendar"}:
        return {
            "method": "mcp",
            "ref": "google-workspace",
            "scopes": ["read"],
            "note": "Pointer only; no credential is versioned.",
        }
    if platform in {"web", "chatgpt"}:
        return {
            "method": "mcp",
            "ref": "browser",
            "scopes": ["read"],
            "note": "Uses the operator's existing authorized browser session.",
        }
    if platform == "repo":
        return {
            "method": "none",
            "ref": "",
            "scopes": [],
            "note": "Reads the repository or configured remote without storing a credential.",
        }
    return {
        "method": "none",
        "ref": "",
        "scopes": [],
        "note": "RAW is supplied locally; no credential belongs in the recipe.",
    }


def operational_recipe_block(
    config_values: dict[str, Any], linked_sources: list[dict[str, Any]]
) -> str:
    """Build an executable recipe only from already-versioned source facts."""
    primary = linked_sources[0] if linked_sources else {}
    platform, _ = infer_platform({**config_values, **primary})
    locator, locator_is_todo = infer_locator(
        str(primary.get("_rel") or ""), {**config_values, **primary}, platform
    )
    if locator_is_todo:
        locator = str(
            primary.get("_rel") or config_values.get("moc_parent") or "source-config"
        )
    cadence = _positive_int(
        primary.get("refresh_cadence_days"),
        primary.get("stale_after_days"),
        config_values.get("stale_after_days"),
    )
    config_targets = _list_values(config_values.get("target_pages")) + _list_values(
        config_values.get("related_pages")
    )
    streams: list[dict[str, Any]] = []
    for index, source in enumerate(linked_sources or [primary], start=1):
        source_id = str(source.get("page_id") or f"source-{index}")
        source_targets = (
            config_targets
            + _list_values(source.get("related_pages"))
            + _list_values(source.get("evidence_refs"))
            + ([str(source.get("moc_parent"))] if source.get("moc_parent") else [])
        )
        streams.append(
            {
                "id": source_id.removeprefix("fonte-")
                .removeprefix("sources-")
                .removeprefix("source-"),
                "label": str(source.get("title") or source_id),
                "selected": True,
                "privacy": _privacy({**config_values, **source}),
                "cadence_days": _positive_int(
                    source.get("refresh_cadence_days"), default=0
                ),
                "filters": {"source_ref": source_id},
                "target_pages": list(
                    dict.fromkeys(target for target in source_targets if target)
                ),
            }
        )
    refresh_policy = str(primary.get("refresh_policy") or "on_demand").strip().lower()
    schedule_mode = (
        refresh_policy
        if refresh_policy in {"one_shot", "on_demand", "recurring", "event_driven"}
        else "on_demand"
    )
    recipe = {
        "recipe": {
            "schema_version": "wiki_source_recipe.v1",
            "platform": platform,
            "locator": locator,
            "source_kind": infer_source_kind(platform),
            "pipelines": [{"kind": "content", "cadence_days": cadence}],
            "streams": streams,
            "auth": _operator_auth(platform),
            "schedule": {
                "mode": schedule_mode,
                "cadence_days": cadence if schedule_mode == "recurring" else 0,
                "cron_hint": "",
            },
            "how_to_export": (
                "Use the source-specific ingestion and privacy rules documented on this "
                "page. Bring authorized RAW or live readback into data/raw, preserve "
                "provenance, then run deterministic extraction before contextual reading."
            ),
            "ingest": {
                "argv": [
                    "python3",
                    "scripts/wiki_ingest.py",
                    "--source",
                    "{path}",
                    "--context",
                    str(config_values.get("context") or "system"),
                ]
            },
        }
    }
    dumped = yaml.safe_dump(recipe, sort_keys=False, allow_unicode=True).rstrip("\n")
    return "## Recipe\n\n```yaml\n" + dumped + "\n```\n"


def _plan_source_page(
    root: Path,
    rel: str,
    values: dict[str, Any],
    today: dt.date,
    *,
    operational: bool = False,
) -> SourceMigrationChange:
    config_values = _config_page_values(root, values)
    additions: dict[str, Any] = {}
    notes: list[str] = []

    if not str(values.get("platform") or "").strip():
        platform, guessed = infer_platform(values)
        additions["platform"] = platform
        if guessed:
            notes.append(f"platform guessed as `{platform}` — confirm")
    else:
        platform = str(values.get("platform")).strip()

    if not str(values.get("source_locator") or "").strip():
        locator, is_todo = infer_locator(rel, values, platform)
        if operational and is_todo:
            locator, is_todo = rel, False
        additions["source_locator"] = locator
        if is_todo:
            notes.append("source_locator is a TODO placeholder — set the real id")

    if not str(values.get("owner") or "").strip():
        owner = infer_owner(values, config_values)
        if owner:
            additions["owner"] = owner
        else:
            notes.append("owner could not be inferred — set it manually")

    # Only add `sync` when the key is genuinely ABSENT. A present-but-scalar/list
    # sync is left alone (adding would duplicate the YAML key and clobber it) and
    # noted for the reviewer instead.
    if "sync" not in values:
        if not operational:
            additions["sync"] = initial_sync(values)
        else:
            lifecycle = (
                values.get("source_lifecycle")
                if isinstance(values.get("source_lifecycle"), dict)
                else {}
            )
            lifecycle_success = lifecycle.get("last_sync_success_at") or lifecycle.get(
                "last_ingested_at"
            )
            # A populated lifecycle is newer than legacy top-level fields. An
            # explicit empty success date must not revive old mutable evidence.
            last_run_at = str(
                lifecycle_success
                or (values.get("last_ingested_at") if not lifecycle else "")
                or ""
            )
            log_refs = lifecycle.get("secret_safe_log_refs")
            path_refs = (
                [
                    str(ref).strip()
                    for ref in log_refs
                    if isinstance(ref, str)
                    and str(ref).strip().endswith(".md")
                    and not str(ref).strip().startswith(("http://", "https://"))
                ]
                if isinstance(log_refs, list)
                else []
            )
            additions["sync"] = {
                "last_run_at": last_run_at,
                "last_status": "ok" if last_run_at else "never",
                "last_event_ref": path_refs[-1] if path_refs else "",
            }
    elif not isinstance(values.get("sync"), dict):
        notes.append("`sync` exists but is not a mapping — fix it by hand")

    return SourceMigrationChange(
        rel=rel, page_type="source", add_frontmatter=additions, notes=tuple(notes)
    )


def _plan_source_config_page(
    root: Path,
    rel: str,
    values: dict[str, Any],
    text: str,
    linked_sources: list[dict[str, Any]] | None = None,
    *,
    operational: bool = False,
) -> SourceMigrationChange:
    # Inherit platform/locator from the source page this config governs, so the
    # recipe matches the entity instead of guessing from the thin config page.
    linked_sources = linked_sources or []
    source = linked_sources[0] if linked_sources else {}
    platform, guessed = infer_platform({**values, **source})
    additions = {} if str(values.get("platform") or "").strip() else {"platform": platform}
    # A pre-existing recipe is canonical and must never be rewritten, except
    # for the exact untouched scaffold generated by this module. That narrow
    # promotion lets a later --operational-recipes pass finish an earlier
    # scaffold migration without risking user-authored recipes.
    existing_recipe = extract_recipe_mapping(text)
    if existing_recipe is not None:
        generated_scaffold = (
            _generated_scaffold_in_text(text, existing_recipe) if operational else ""
        )
        if generated_scaffold:
            return SourceMigrationChange(
                rel=rel,
                page_type="source_config",
                add_frontmatter=additions,
                replace_recipe_from=generated_scaffold,
                replace_recipe_with=operational_recipe_block(values, linked_sources),
                notes=(
                    "promoted the untouched framework TODO scaffold to an operational recipe",
                ),
            )
        return SourceMigrationChange(
            rel=rel,
            page_type="source_config",
            add_frontmatter=additions,
        )
    if operational:
        return SourceMigrationChange(
            rel=rel,
            page_type="source_config",
            add_frontmatter=additions,
            append_recipe=operational_recipe_block(values, linked_sources),
            notes=(
                "generated selected streams from existing source_refs, targets, privacy and cadence",
            ),
        )
    locator, is_todo = infer_locator(
        source.get("_rel", rel), {**source, **values}, platform
    )
    notes: list[str] = ["scaffolded a TODO recipe — complete the streams + export steps"]
    if guessed:
        notes.append(f"recipe platform guessed as `{platform}` — confirm")
    if is_todo:
        notes.append("recipe locator is a TODO placeholder — set the real id")
    return SourceMigrationChange(
        rel=rel,
        page_type="source_config",
        add_frontmatter=additions,
        append_recipe=scaffold_recipe_block(platform, locator),
        notes=tuple(notes),
    )


def plan_source_migration(
    root: Path,
    config: WikiConfig,
    today: dt.date | None = None,
    *,
    operational_recipes: bool = False,
) -> list[SourceMigrationChange]:
    """Scan ``memories/`` and return the additive changes needed to bring every
    source / source_config page up to contract. Empty changes are dropped."""
    today = today or dt.date.today()
    memory_root = root / str(config.paths.get("memory_root") or "memories")
    if not memory_root.exists():
        return []
    md_paths = sorted(memory_root.rglob("*.md"))

    # Index source pages by page_id so a source_config can inherit its entity's
    # platform/locator instead of guessing from the thin config page.
    source_by_id: dict[str, dict[str, Any]] = {}
    sources_by_config_ref: dict[str, list[dict[str, Any]]] = {}
    for path in md_paths:
        values = parse_frontmatter(path)[0]
        if str(values.get("page_type") or "") == "source":
            page_id = str(values.get("page_id") or "").strip()
            if page_id:
                indexed = {**values, "_rel": path.relative_to(root).as_posix()}
                source_by_id[page_id] = indexed
                config_ref = str(values.get("config_ref") or "").strip()
                if config_ref:
                    sources_by_config_ref.setdefault(config_ref, []).append(indexed)

    changes: list[SourceMigrationChange] = []
    for path in md_paths:
        values = parse_frontmatter(path)[0]
        page_type = str(values.get("page_type") or "")
        rel = path.relative_to(root).as_posix()
        if page_type == "source":
            change = _plan_source_page(
                root, rel, values, today, operational=operational_recipes
            )
        elif page_type == "source_config":
            refs = values.get("source_refs")
            linked: list[dict[str, Any]] = list(sources_by_config_ref.get(rel, []))
            linked_ids = {str(source.get("page_id") or "") for source in linked}
            for ref in refs if isinstance(refs, list) else []:
                if str(ref) in source_by_id and str(ref) not in linked_ids:
                    linked.append(source_by_id[str(ref)])
                    linked_ids.add(str(ref))
            change = _plan_source_config_page(
                root,
                rel,
                values,
                path.read_text(encoding="utf-8"),
                linked,
                operational=operational_recipes,
            )
        else:
            continue
        if not change.is_empty():
            changes.append(change)
    return changes


def insert_frontmatter_keys(text: str, additions: dict[str, Any]) -> str:
    """Append keys to the frontmatter block, just before its closing ``---``,
    preserving the existing field order and body verbatim. Creates a frontmatter
    block if the page has none. Keys ALREADY present are dropped, never appended,
    so we can't produce a duplicate YAML key that silently clobbers a value."""
    if not additions:
        return text
    match = FRONTMATTER_RE.match(text)
    if not match:
        dumped = yaml.safe_dump(additions, sort_keys=False, allow_unicode=True).rstrip("\n")
        return f"---\n{dumped}\n---\n\n{text}"
    inner = match.group(1)
    try:
        existing = yaml.safe_load(inner)
    except yaml.YAMLError:
        existing = None
    present = set(existing) if isinstance(existing, dict) else set()
    fresh = {k: v for k, v in additions.items() if k not in present}
    if not fresh:
        return text
    dumped = yaml.safe_dump(fresh, sort_keys=False, allow_unicode=True).rstrip("\n")
    return f"---\n{inner.rstrip(chr(10))}\n{dumped}\n---\n" + text[match.end() :]


def apply_change(root: Path, change: SourceMigrationChange) -> None:
    """Write one planned change, failing closed if a scaffold drifted."""
    path = root / change.rel
    text = path.read_text(encoding="utf-8")
    if change.add_frontmatter:
        text = insert_frontmatter_keys(text, change.add_frontmatter)
    if change.replace_recipe_from or change.replace_recipe_with:
        if not change.replace_recipe_from or not change.replace_recipe_with:
            raise ValueError("recipe replacement requires both source and destination blocks")
        if text.count(change.replace_recipe_from) != 1:
            raise RuntimeError(
                f"refusing recipe promotion after scaffold drift: {change.rel}"
            )
        text = text.replace(
            change.replace_recipe_from, change.replace_recipe_with, 1
        )
    if change.append_recipe:
        separator = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
        text = f"{text}{separator}{change.append_recipe}"
    path.write_text(text, encoding="utf-8")
