#!/usr/bin/env python3
"""Generate the canonical-source registry page (deterministic).

The registry is a versioned page, linked from the root index, with one row per
canonical source page: its link, type, ingestion state and last update. Each
source PAGE is the hierarchical node that holds that source's ingestion log, so
the registry is the index INTO those per-source logs.

`--write` regenerates the page (stamping today's date); `--check` regenerates
using the page's own recorded date and fails if the content diverges (CI gate,
like the operation cockpit). The build is deterministic: same repo, same page.
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from wiki_core.config import freshness_for, load_config
from wiki_core.paths import WikiPaths

# Source page_types that count as a canonical source in the registry.
SOURCE_PAGE_TYPES = {"source", "source_catalog", "artifact"}
# Strings per language for the generated page (driven by config.language).
STRINGS = {
    "pt": {
        "title": "Registro de fontes canonicas",
        "purpose": "Indice das fontes canonicas: link, tipo, estado de ingestao e ultima atualizacao.",
        "updated": "Atualizado em: {date}.",
        "intro": (
            "Cada fonte canonica e uma pagina (o no hierarquico que guarda o log de "
            "ingestao da fonte). Esta pagina e gerada por "
            "[scripts/wiki_source_registry.py]({script}); nao edite a mao."
        ),
        "th": "| Fonte | Tipo | Estado | Ultima atualizacao |",
        "empty": "_Nenhuma fonte canonica registrada ainda._",
        "state_default": "—",
        "back": "Voltar ao indice em [{index}]({index_link}).",
    },
    "en": {
        "title": "Canonical source registry",
        "purpose": "Index of canonical sources: link, type, ingestion state and last update.",
        "updated": "Updated at: {date}.",
        "intro": (
            "Each canonical source is a page (the hierarchical node that holds that "
            "source's ingestion log). This page is generated by "
            "[scripts/wiki_source_registry.py]({script}); do not hand-edit."
        ),
        "th": "| Source | Type | State | Last update |",
        "empty": "_No canonical sources registered yet._",
        "state_default": "—",
        "back": "Back to the index at [{index}]({index_link}).",
    },
}


def _strings(language: str) -> dict[str, str]:
    return STRINGS.get(language, STRINGS["en"])


def read_frontmatter(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    try:
        return yaml.safe_load(text[4:end]) or {}
    except yaml.YAMLError:
        return {}


def collect_sources(paths: WikiPaths) -> list[dict[str, str]]:
    """One row per canonical source page under the sources dir, sorted by title."""
    sources_dir = paths.sources_dir
    rows: list[dict[str, str]] = []
    if not sources_dir.is_dir():
        return rows
    for md in sorted(sources_dir.glob("*.md")):
        if md.name in {"index.md", "README.md"}:
            continue
        fm = read_frontmatter(md)
        page_type = str(fm.get("page_type", ""))
        if page_type not in SOURCE_PAGE_TYPES:
            continue
        title = str(fm.get("title") or fm.get("page_id") or md.stem)
        rows.append(
            {
                "title": title,
                "rel": paths.rel(md),
                "type": str(fm.get("source_type") or page_type),
                "state": str(fm.get("ingestion_state") or ""),
                "updated": str(fm.get("last_ingested_at") or fm.get("updated_at") or ""),
            }
        )
    rows.sort(key=lambda r: (r["title"].lower(), r["rel"]))
    return rows


def build_registry(paths: WikiPaths, config, updated_at: str) -> str:
    s = _strings(config.language)
    reg_path = paths.source_registry_page
    reg_dir = reg_path.parent

    def link_to(rel: str) -> str:
        href = os.path.relpath(ROOT / rel, reg_dir).replace(os.sep, "/")
        return href

    rows = collect_sources(paths)
    index_rel = paths.rel(paths.memory_root / "index.md")
    script_link = os.path.relpath(ROOT / "scripts" / "wiki_source_registry.py", reg_dir).replace(os.sep, "/")

    body: list[str] = [
        "---",
        "page_id: source-registry",
        "page_type: source_registry",
        f'title: "{s["title"]}"',
        f"context: {config.default_context}",
        "visibility: private_self",
        f"updated_at: {updated_at}",
        f"stale_after_days: {freshness_for(config.default_context, 'source_registry', config)}",
        "sources_policy: memoria_consolidada",
        "gate: github_pr",
        "sensitive_data_policy: private_sensitive_allowed",
        f"moc_parent: {index_rel}",
        "---",
        "",
        f"# {s['title']}",
        "",
        s["updated"].format(date=updated_at),
        "",
        s["purpose"],
        "",
        s["intro"].format(script=script_link),
        "",
    ]
    if rows:
        body.append(s["th"])
        body.append("| --- | --- | --- | --- |")
        for r in rows:
            state = r["state"] or s["state_default"]
            updated = r["updated"] or s["state_default"]
            body.append(
                f"| [{r['title']}]({link_to(r['rel'])}) | `{r['type']}` | {state} | {updated} |"
            )
    else:
        body.append(s["empty"])
    body.append("")
    body.append(s["back"].format(index=index_rel, index_link=link_to(index_rel)))
    body.append("")
    return "\n".join(body)


def _recorded_date(path: Path, fallback: str) -> str:
    if not path.exists():
        return fallback
    value = read_frontmatter(path).get("updated_at")
    return str(value) if value else fallback


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true", help="write the registry page")
    parser.add_argument("--check", action="store_true", help="fail if the page is out of date (CI)")
    parser.add_argument("--date", default=dt.date.today().isoformat())
    args = parser.parse_args()

    config = load_config(ROOT)
    paths = WikiPaths(ROOT, config)
    target = paths.source_registry_page

    if args.check:
        if not target.exists():
            print(f"ERROR: {paths.rel(target)} does not exist (run --write)", file=sys.stderr)
            return 1
        expected = build_registry(paths, config, _recorded_date(target, args.date))
        actual = target.read_text(encoding="utf-8")
        if expected != actual:
            print(f"{paths.rel(target)}: registry is out of date — run wiki_source_registry.py --write", file=sys.stderr)
            return 1
        print(f"{paths.rel(target)}: source registry up to date.")
        return 0

    content = build_registry(paths, config, args.date)
    if args.write:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        print(paths.rel(target))
        return 0
    print(content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
